
SELECT DISTINCT 
     '003' MEASURE_ID
     ,PATIENT_CODE   CLIENTID
     ,SOC
     ,CONCAT(TO_CHAR(CERT_END_DATE,'yyyy'),TO_CHAR(CERT_END_DATE,'mm')) AS MONTH_ID
     ,CERT_END_DATE      THE_DATE
     ,'CERT_END_DATE'    DATE_TYPE
     ,ASSESS_DATE
     ,MANAGERID       STAFF_ID
     ,COMPANYID       COMPANY_ID
     ,CASE
           WHEN ASSESS_DATE BETWEEN START_DATE_FOR_ASSESS AND CERT_END_DATE THEN 1
           ELSE 0
           END AS NUM
          , 1  AS DEN   
FROM 
 ( 
 SELECT PATIENT_CODE
       ,CHARTID
       ,CERT_START_DATE
       ,CERT_END_DATE
       ,COMPANYID
       ,SOC
       ,EOC
       ,DATE_MODIFIED
       ,START_DATE_FOR_ASSESS
       ,CERTIFICATION_NUMBER
       ,ASSESS_DATE
       ,MANAGERID
       ,CAREGIVER_CODE
       ,FORM_STATUS
       ,RK
FROM 
    (
    SELECT DEN.PATIENT_CODE
           ,DEN.CHARTID
           ,TO_DATE(DEN.START_DATE,'YYYYMMDD')   CERT_START_DATE
           ,TO_DATE(DEN.END_DATE,'YYYYMMDD')     CERT_END_DATE
           ,DEN.COMPANYID
           ,DEN.SOC
           ,DEN.EOC 
           ,DEN.DATE_MODIFIED
           ,DEN.START_DATE_FOR_ASSESS
           ,DEN.CERTIFICATION_NUMBER
           ,TO_DATE(NUM.VISIT_DATE, 'YYYYMMDD')    ASSESS_DATE
           ,DEN.MANAGERID
           ,NUM.CAREGIVER_CODE
           ,NUM. FORM_STATUS
           ,RANK ()
                  OVER ( PARTITION BY DEN.PATIENT_CODE,DEN.CHARTID,DEN.COMPANYID,DEN.SOC,
                   TO_DATE(DEN.START_DATE,'YYYYMMDD'),TO_DATE(DEN.END_DATE,'YYYYMMDD')
                  ORDER BY TO_DATE(NUM.VISIT_DATE, 'YYYYMMDD') DESC) RK
FROM
    (
    SELECT DISTINCT C.*, to_date(end_date,'YYYYMMDD')-21 start_date_for_assess, A.COMPANYID, A.SOC, A.EOC,A.CHARTID,A.MANAGERID
    FROM PIC.SPOC_PATIENT_CERTIFICATION_PERIOD C
    JOIN PIC.PATIENT_ADMISSIONS A
      ON  A.CLIENTID = C.PATIENT_CODE 
      AND TO_DATE(C.START_DATE, 'YYYYMMDD')  BETWEEN A.SOC AND NVL(A.EOC,SYSDATE) 
    WHERE  C.REMOVED = 'N' 
           AND SUBSTR(A.CHARTID,-3,2)!= 'KD'
           AND TO_DATE(C.END_DATE,'YYYYMMDD') BETWEEN '01-JUL-2020' AND sysdate 
           AND TO_DATE(C.END_DATE,'YYYYMMDD') != NVL(A.EOC,SYSDATE+10)                                      
           ) DEN                               
 LEFT JOIN
    (
      SELECT SP.*,C.MR_NUMBER,C.START_OF_CARE
     FROM  PIC.SPOC_FORM  SP
     JOIN PIC.SPOC_PATIENT_CHART C
           ON C.PATIENT_CODE = SP.PATIENT_CODE
          AND C.CHART_NUMBER = SP.CHART_NUMBER
     WHERE form_name in ( 'Adult Assessment Recert',
                          'Adult Assessment - Recert')
       AND SP.REMOVED = 'N'
       AND FORM_STATUS != 'Pending'                                                                                       
      ) NUM
    ON DEN.PATIENT_CODE = NUM.PATIENT_CODE
     AND DEN.CHARTID = NUM.MR_NUMBER
   AND TO_DATE(NUM.VISIT_DATE,'YYYYMMDD') BETWEEN DEN.SOC AND NVL(DEN.EOC,SYSDATE)
   AND TO_DATE(NUM.VISIT_DATE,'YYYYMMDD') BETWEEN TO_DATE(DEN.START_DATE,'YYYYMMDD') AND TO_DATE(END_DATE,'YYYYMMDD')
 --  AND DEN.CERTIFICATION_NUMBER = NUM.CERTIFICATION_NUMBER 
)
WHERE RK =1
)




   