SELECT DISTINCT 
     '005' MEASURE_ID
     ,PATIENT_CODE  CLIENTID
     ,SOC
     ,CONCAT(TO_CHAR(VISIT_DATE,'yyyy'),TO_CHAR(VISIT_DATE,'mm')) AS MONTH_ID
     ,VISIT_DATE AS  THE_DATE
     ,'Supervisory_Visit'  DATE_TYPE
     ,VISIT_DATE       ASSESS_DATE
     ,CAREGIVER_CODE   STAFF_ID
     ,COMPANYID        COMPANY_ID
     ,CASE
           WHEN (FORM_NAME IN ('Nursing Visit Note')
                  AND FORM_FIELD_VALUE = 1) THEN 1
           ELSE 0
           END AS NUM
          , 1  AS DEN   
FROM 
(
SELECT SP.CAREGIVER_CODE, SP.FORM_NAME
       ,TO_DATE(SP.VISIT_DATE,'YYYYMMDD') VISIT_DATE
       ,SP.PATIENT_CODE
       ,SP.DATE_CREATED
       ,SP.FORM_STATUS 
       ,A.COMPANYID
       ,A.CHARTID
       ,A.SOC
       ,A.EOC
       ,F.FORM_FIELD_NAME
       ,F.FORM_FIELD_VALUE
       ,U.PRIMARY_USER_TYPE
FROM PIC.SPOC_FORM  SP
JOIN PIC.SPOC_FORM_NEWFIELDS_V F
    ON SP.FORM_ID = F.FORM_ID 
   AND (UPPER(F.FORM_FIELD_NAME) = UPPER('Supervision performed this visit'))
   AND REMOVED ='N'
JOIN PIC.PATIENT_ADMISSIONS A
    ON A.clientid = SP.PATIENT_CODE
   AND TO_DATE(SP.VISIT_DATE,'YYYYMMDD') BETWEEN A.SOC AND NVL(A.EOC,SYSDATE)
JOIN PIC.SPOC_USERS U
    ON U.CAREGIVER_CODE = SP.CAREGIVER_CODE     
WHERE  SP.FORM_STATUS != 'Pending'  
       AND SUBSTR(A.CHARTID,-3,2)!= 'KD'
       AND COMPANYID = 8  --- PVT
       AND TO_DATE(SP.VISIT_DATE,'YYYYMMDD') BETWEEN TO_DATE('7/01/2020', 'mm/dd/yyyy') AND TO_DATE('7/31/2020', 'mm/dd/yyyy')
 )