 SELECT SP.*,C.MR_NUMBER,C.START_OF_CARE, AD.SOC, AD.ROC,AD.EOC, AD.CHARTID, AD.COMPANYID,
         AU.AGENCYID, AU.AUTHID, AU.ADMISSIONID, AU.PERIODID, 
       AU.PAYORID, AU.SERVICEID, AU.EVENTID,AU.AUTHREFNO,
       AU.DATEBEGIN, AU.DATEEND,
       E.DESCRIPTION, E.ISACTIVE, E.ISBILLABLE, E.ISPAYABLE
    --   , CASE WHEN 
     FROM  PIC.SPOC_FORM    SP
     JOIN PIC.SPOC_PATIENT_CHART   C
       ON C.PATIENT_CODE = SP.PATIENT_CODE
      AND C.CHART_NUMBER = SP.CHART_NUMBER           
     JOIN PIC.PATIENT_ADMISSIONS   AD
       ON AD.CLIENTID = SP.PATIENT_CODE
      AND TO_DATE(SP.VISIT_DATE,'YYYYMMDD') BETWEEN AD.SOC AND NVL(AD.EOC,SYSDATE)
      AND C.MR_NUMBER = AD.CHARTID
     JOIN PIC.AUTHORIZATIONS AU
       ON AU.ADMISSIONID = AD.ADMISSIONID
     JOIN PIC.EVENTS E
        ON E.EVENTCODE = AU.EVENTID
  WHERE form_name in ( 'Adult Assessment SOC')
      AND SP.REMOVED = 'N'
      AND FORM_STATUS != 'Pending'  
      AND COMPANYID = 11   
   --    and CHARTID = 'M0130814-KNS'
       




select * from PIC.EVENTS

select * from PIC.SERVICES


select AU.AGENCYID, AU.AUTHID, AU.ADMISSIONID, AU.PERIODID, 
       AU.PAYORID, AU.SERVICEID, AU.EVENTID,AU.AUTHREFNO,
       AU.DATEBEGIN, AU.DATEEND
from PIC.AUTHORIZATIONS AU
JOIN PIC.PATIENT_ADMISSIONS   AD
  ON AU.ADMISSIONID = AD.ADMISSIONID
  
  
      
      
      