SELECT SUBSCRIBER_ID, MONTH_ID, PROGRAM, MEMBER_ID,AGE, DL_LOB_ID, LOB_ID, LINE_OF_BUSINESS, DISENROLLMENT_DATE, ENROLLED_FLAG, DISENROLLED_FLAG, BOROUGH, MAP_REGION_NAME,DL_ENROLL_ID,
       PRODUCT_ID,PRODUCT_NAME,GROUP_ID, GROUP_NAME, PLAN_ID,PLAN_DESC,PLAN_PACKAGE,SUBGROUP_ID, SUBGROUP_NAME,RATE_CODE,REGION_NAME,REGION_NAME2,COUNTY, COUNTY_CODE,UAS_RECORD_ID,
       REPORTING_DATE,DL_ENRL_SK,DL_ASSESS_SK,DL_MEMBER_ADDRESS_SK,DL_DISABLED_SK,DL_DELEGATED_CM_SK,MOBILITY_DEVICE_IND,ICS_IND,CASE_NBR,CM_SK_ID,DC_REASON,DISENROLL_DISP,DISENROLL_RSN_DESC,
       RISK_SCORE,MRN,DL_MEMBER_SK,DL_PLAN_SK,DL_PMPM_ENR_SK,DL_PROV_SK,STAFF_ID,STATE_CODE,UAS_DATE,TO_NUMBER(UAS_NFLOC_SCORE)
 -- VPIN, RACE, DATE_OF_BIRTH, SSN, FIRST_NAME, LAST_NAME, SEX, ENROLLMENT_DATE, REFERRAL_DATE ,BENEFIT_REGION, MEDICAID_NUM,MEDICARE_NUM, LTP_IND,RATE_CODE_DESC,(CARE_STAFF_NAME),
 --DL_COUNTY_SK,  MANDATORY_ENROLLMENT
FROM CHOICEBI.FACT_MEMBER_MONTH
MINUS
select SUBSCRIBER_ID, REPORTING_MONTH, PROGRAM, MEMBER_ID, AGE, DL_LOB_ID, DL_LOB_ID, LOB , DISENROLLMENT_DATE, NEW_ENR_IND, NEW_DISENR_IND, BOROUGH, MAP_REGION_NAME, DL_ENROLL_ID,
       PRODUCT_ID,PRODUCT_NAME,GROUP_ID, GROUP_NAME, PLAN_ID,PLAN_DESC,PLAN_PACKAGE,SUB_GROUP_ID,SUB_GROUP_NAME,RATE_CODE,REGION_NAME,REGION_NAME2,COUNTY, COUNTY_CODE,UAS_RECORD_ID,
       REPORTING_MONTH_DATE,DL_ENRL_SK,DL_ASSESS_SK,DL_MEMBER_ADDRESS_SK,DL_DISABLED_SK,DELEGATED_CM_SK,MOBILITY_DEVICE_IND,ICS_IND,CASE_NBR,CM_SK_ID,DISENROLL_RSN_CODE,DISENROLL_RSN_DESC,DISENROLL_RSN_DESC,
       MLTC_UAS_PREMIUM_RISK_SCORE ,MRN,DL_MEMBER_SK,DL_PLAN_SK,DL_PMPM_ENR_SK,DL_PROV_SK,CARE_MANAGER_ID,STATE,UAS_DATE,UAS_NFLOC_SCORE
--  VPIN, RACE, DOB, SSN, FIRST_NAME, LAST_NAME, GENDER, ORIG_ENROLLMENT_START_DT, REFERRAL_DATE, BENEFIT_REGION, MEDICAID, CURRENT_MEDICARE, LTP_IND,RATE_CODE_DESC,(CARE_MANAGER_FIRST_NAME || CARE_MANAGER_LAST_NAME),
--DL_COUNTY_SK, MANDATORY_ENROLLMENT
FROM CHOICE.FACT_MEMBER_MONTH@DLAKE
;