select DISTINCT SUBSCRIBER_ID,REPORTING_MONTH,LTP_IND,DL_LOB_ID,LOB
 FROM CHOICE.FACT_MEMBER_MONTH@dlake
WHERE LOB = 'MAP'
--where SUBSCRIBER_ID = 'V70000096'--AND REPORTING_MONTH = 201902
 MINUS
select DISTINCT SUBSCRIBER_ID, MONTH_ID, TO_NUMBER(LTP_IND), LOB_ID, LINE_OF_BUSINESS
from choicebi.fact_member_month
WHERE LINE_OF_BUSINESS ='MAP'
--where SUBSCRIBER_ID IN ( 'V70000096')--AND MONTH_ID = 201902
;




select F.SUBSCRIBER_ID CADM_SUBSCRIBER_ID, K.SUBSCRIBER_ID CHICEBI_SUBSCRIBER_ID,
     F.REPORTING_MONTH,K.MONTH_ID,
    F.LTP_IND CADM_LTP,K.LTP_IND CHICE_LTP, 
    F.DL_LOB_ID  CADM_LOB_ID,K.LOB_ID  CHICE_LOB_ID,
    F.LOB CADM_LOB, K.LINE_OF_BUSINESS  CHOICE_LOB,
    F.PROGRAM  CADM_PROGRAM, k.program  CHICE_PROGRAM
 FROM CHOICE.FACT_MEMBER_MONTH@DLAKE F
 LEFT JOIN CHOICEBI.FACT_MEMBER_MONTH K on (k.month_id = F.REPORTING_MONTH and K.SUBSCRIBER_ID = F.SUBSCRIBER_ID --and F.program = k.program
 )
WHERE  F.LTP_IND != K.LTP_IND;  ---744
 


select F.SUBSCRIBER_ID CADM_SUBSCRIBER_ID, K.SUBSCRIBER_ID CHICEBI_SUBSCRIBER_ID,
     F.REPORTING_MONTH,K.MONTH_ID,
    F.LTP_IND CADM_LTP,K.LTP_IND CHICE_LTP, LTP.LTP_IND  LTP_LTP,
    F.DL_LOB_ID  CADM_LOB_ID,K.LOB_ID  CHICE_LOB_ID,
    F.LOB CADM_LOB, K.LINE_OF_BUSINESS  CHOICE_LOB,
    F.PROGRAM  CADM_PROGRAM, k.program  CHICE_PROGRAM
 FROM CHOICE.FACT_MEMBER_MONTH@DLAKE F
 LEFT JOIN CHOICEBI.FACT_MEMBER_MONTH K on (k.month_id = F.REPORTING_MONTH and K.SUBSCRIBER_ID = F.SUBSCRIBER_ID and F.program = k.program
 )
 LEFT JOIN FACT_HHA_LTP_MONTHLY_DATA LTP ON(LTP.month_id = F.REPORTING_MONTH and LTP.SUBSCRIBER_ID = F.SUBSCRIBER_ID)
WHERE  F.program !=k.program ;--249,810
 
 






SELECT * FROM FACT_HHA_LTP_MONTHLY_DATA;
    
    
    
    
