SELECT  distinct 'Case Rate' PROGRAM,
       E.PATIENT_ID, E.FIRST_NAME, E.LAST_NAME,D.BIRTH_YEAR,E.EPI_START_DATE,E.EPI_END_DATE, D.ADDRESS,D.CITY,D.STATE,D.ZIP, L.LANGUAGE_NAME,PLAN_DESC
FROM POP_HEALTH_BI.VW_FACT_PHGC_TIME_BASED_EPI E
JOIN PHGC.PATIENT_DETAILS D ON E.PATIENT_ID = D.PATIENT_ID
LEFT JOIN  PHGC.LANGUAGE  L     ON D.PRIMARY_LANGUAGE_ID = L.LANGUAGE_ID
WHERE  NVL (E.epi_end_date, '31-dec-9999') >= TO_DATE('12/1/2020','MM/DD/YYYY')