
DROP MATERIALIZED VIEW CHOICEBI.MV_DIM_F9_AGENT_SKILL_MAP;

CREATE MATERIALIZED VIEW CHOICEBI.MV_DIM_F9_AGENT_SKILL_MAP
REFRESH FORCE
NEXT TRUNC(SYSDATE) + 1.28
WITH PRIMARY KEY
AS
SELECT DISTINCT C.DL_SKILL_SK, A.* FROM
(
SELECT AGENT_ID,
AGENT_ID DL_AGENT_SK,
AGENT_EMAIL,
SKILL
FROM V_DIM_F9_AGENT_SKILL_MAP
WHERE SKILL IS NOT NULL
) A
JOIN MV_DIM_F9_SKILL C ON (A.SKILL = C.SKILL);
COMMENT ON MATERIALIZED VIEW CHOICEBI.MV_DIM_F9_CAMPAIGN_SKILL_MAP IS 'snapshot table for snapshot CHOICEBI.MV_DIM_F9_CAMPAIGN_SKILL_MAP';
GRANT SELECT ON CHOICEBI.MV_DIM_F9_CAMPAIGN_SKILL_MAP TO CHOICEBI_RO_NEW;
GRANT SELECT ON CHOICEBI.MV_DIM_F9_CAMPAIGN_SKILL_MAP TO MSTRSTG;
