



DROP MATERIALIZED VIEW CHOICEBI.MV_FACT_F9_ACD_QUEUE;

CREATE MATERIALIZED VIEW CHOICEBI.MV_FACT_F9_ACD_QUEUE as
SELECT DISTINCT
       CALL_ID,
       SERVICE_LEVEL, 
       A.SKILL,
       S.DL_SKILL_SK,
       A.CAMPAIGN,
       C.DL_CAMPAIGN_SK,
       SPEED_OF_ANSWER,
         (TO_NUMBER ( SUBSTR( SPEED_OF_ANSWER, 1, INSTR( SPEED_OF_ANSWER, ':', 1, 1 ) - 1  )) * 60 * 60)
       + (TO_NUMBER (SUBSTR( SPEED_OF_ANSWER, INSTR( SPEED_OF_ANSWER, ':', 1, 1 ) + 1, INSTR( SPEED_OF_ANSWER, ':', 1, 2 ) - INSTR( SPEED_OF_ANSWER, ':', 1, 1 ) - 1 )) * 60)
      + (TO_NUMBER (SUBSTR( SPEED_OF_ANSWER, INSTR( SPEED_OF_ANSWER, ':', 1, 2 ) + 1, INSTR( SPEED_OF_ANSWER, ':', 1, 2 ) - INSTR( SPEED_OF_ANSWER, ':', 1, 1 ) - 1 )))
           AS SPEED_OF_ANSWER_IN_SECONDS,
       ABANDONED,
       TIME_TO_ABANDON,
         (TO_NUMBER ( SUBSTR( TIME_TO_ABANDON, 1, INSTR(TIME_TO_ABANDON, ':', 1, 1 ) - 1  )) * 60 * 60)
       + (TO_NUMBER (SUBSTR( TIME_TO_ABANDON, INSTR(TIME_TO_ABANDON, ':', 1, 1 ) + 1, INSTR(TIME_TO_ABANDON, ':', 1, 2 ) - INSTR(TIME_TO_ABANDON, ':', 1, 1 ) - 1 )) * 60)
      + (TO_NUMBER (SUBSTR( TIME_TO_ABANDON, INSTR( TIME_TO_ABANDON, ':', 1, 2 ) + 1, INSTR(TIME_TO_ABANDON, ':', 1, 2 ) - INSTR(TIME_TO_ABANDON, ':', 1, 1 ) - 1 )))
           AS TIME_TO_ABANDON_IN_SECONDS,
       DISPOSITION, DISPOSITION_GROUP_A, DISPOSITION_GROUP_B, DISPOSITION_GROUP_C, DISPOSITION_PATH,
       FIRST_CALL_RESOLUTION,
       QUEUE_WAIT_TIME,
         (TO_NUMBER ( SUBSTR( QUEUE_WAIT_TIME, 1, INSTR( QUEUE_WAIT_TIME, ':', 1, 1 ) - 1  )) * 60 * 60)
       + (TO_NUMBER (SUBSTR( QUEUE_WAIT_TIME, INSTR( QUEUE_WAIT_TIME, ':', 1, 1 ) + 1, INSTR( QUEUE_WAIT_TIME, ':', 1, 2 ) - INSTR( QUEUE_WAIT_TIME, ':', 1, 1 ) - 1 )) * 60)
      + (TO_NUMBER (SUBSTR( QUEUE_WAIT_TIME, INSTR( QUEUE_WAIT_TIME, ':', 1, 2 ) + 1, INSTR( QUEUE_WAIT_TIME, ':', 1, 2 ) - INSTR( QUEUE_WAIT_TIME, ':', 1, 1 ) - 1 )))
           AS QUEUE_WAIT_TIME_IN_SECONDS    
FROM DW_OWNER.F9_ACD_QUEUE A
JOIN MV_DIM_F9_SKILL    S  ON (A.SKILL = S.SKILL)
JOIN MV_DIM_F9_CAMPAIGN C  ON (A.CAMPAIGN = C.CAMPAIGN);

GRANT SELECT ON CHOICEBI.MV_FACT_F9_ACD_QUEUE TO CHOICEBI_RO,CHOICEBI_RO_NEW, LINKADM, LINKADM2, MSTRSTG, ROC_RO, ROC_RO2;






   