DROP MATERIALIZED VIEW CHOICEBI.MV_FACT_F9_CALL_LOG;

CREATE MATERIALIZED VIEW CHOICEBI.MV_FACT_F9_CALL_LOG 
AS 
SELECT DISTINCT
       CALL_ID,
       DATE1,
       TO_TIMESTAMP (SUBSTR (TIMESTAMP1, 6), 'DD MON YYYY HH24:MI:SS')
           TIMESTAMP,
       CALL_TYPE,
       AGENT_ID,
       AGENT_ID
           AGENT_SK,
       CONTACT_ID,
       A.SKILL,
       S.DL_SKILL_SK,
       A.CAMPAIGN,
       C.DL_CAMPAIGN_SK,
       CAMPAIGN_TYPE,
       ABANDONED,
       ANI,
       SERVICE_LEVEL,
       CALLS,
       MANUAL_TIME,
          (TO_NUMBER (SUBSTR(MANUAL_TIME, 1, INSTR(MANUAL_TIME, ':', 1, 1 ) - 1  )) * 60 * 60)
       + (TO_NUMBER (SUBSTR(MANUAL_TIME, INSTR(MANUAL_TIME, ':', 1, 1 ) + 1, INSTR(MANUAL_TIME, ':', 1, 2 ) - INSTR(MANUAL_TIME, ':', 1, 1 ) - 1 )) * 60)
       + (TO_NUMBER (SUBSTR(MANUAL_TIME, INSTR(MANUAL_TIME, ':', 1, 2 ) + 1, INSTR(MANUAL_TIME, ':', 1, 2 ) - INSTR(MANUAL_TIME, ':', 1, 1 ) - 1 )))
           AS MANUAL_TIME_IN_SECONDS,
       HANDLE_TIME,
        (TO_NUMBER (SUBSTR(HANDLE_TIME, 1, INSTR(HANDLE_TIME, ':', 1, 1 ) - 1  )) * 60 * 60)
       + (TO_NUMBER (SUBSTR(HANDLE_TIME, INSTR(HANDLE_TIME, ':', 1, 1 ) + 1, INSTR(HANDLE_TIME, ':', 1, 2 ) - INSTR(HANDLE_TIME, ':', 1, 1 ) - 1 )) * 60)
       + (TO_NUMBER (SUBSTR(HANDLE_TIME, INSTR(HANDLE_TIME, ':', 1, 2 ) + 1, INSTR(HANDLE_TIME, ':', 1, 2 ) - INSTR(HANDLE_TIME, ':', 1, 1 ) - 1 )))
           AS HANDLE_TIME_IN_SECONDS,
       CALL_TIME,
         (TO_NUMBER (SUBSTR(CALL_TIME, 1, INSTR(CALL_TIME, ':', 1, 1 ) - 1  )) * 60 * 60)
       + (TO_NUMBER (SUBSTR(CALL_TIME, INSTR(CALL_TIME, ':', 1, 1 ) + 1, INSTR(CALL_TIME, ':', 1, 2 ) - INSTR(CALL_TIME, ':', 1, 1 ) - 1 )) * 60)
       + (TO_NUMBER (SUBSTR(CALL_TIME, INSTR(CALL_TIME, ':', 1, 2 ) + 1, INSTR(CALL_TIME, ':', 1, 2 ) - INSTR(CALL_TIME, ':', 1, 1 ) - 1 )))
           AS CALL_TIME_IN_SECONDS,
       TALK_TIME,
          (TO_NUMBER (SUBSTR(TALK_TIME, 1, INSTR(TALK_TIME, ':', 1, 1 ) - 1  )) * 60 * 60)
       + (TO_NUMBER (SUBSTR(TALK_TIME, INSTR(TALK_TIME, ':', 1, 1 ) + 1, INSTR(TALK_TIME, ':', 1, 2 ) - INSTR(TALK_TIME, ':', 1, 1 ) - 1 )) * 60)
       + (TO_NUMBER (SUBSTR(TALK_TIME, INSTR(TALK_TIME, ':', 1, 2 ) + 1, INSTR(TALK_TIME, ':', 1, 2 ) - INSTR(TALK_TIME, ':', 1, 1 ) - 1 )))
           AS TALK_TIME_IN_SECONDS,
       BILL_TIME_ROUNDED,
              (TO_NUMBER (SUBSTR(BILL_TIME_ROUNDED, 1, INSTR(BILL_TIME_ROUNDED, ':', 1, 1 ) - 1  )) * 60 * 60)
       + (TO_NUMBER (SUBSTR(BILL_TIME_ROUNDED, INSTR(BILL_TIME_ROUNDED, ':', 1, 1 ) + 1, INSTR(BILL_TIME_ROUNDED, ':', 1, 2 ) - INSTR(BILL_TIME_ROUNDED, ':', 1, 1 ) - 1 )) * 60)
       + (TO_NUMBER (SUBSTR(BILL_TIME_ROUNDED, INSTR(BILL_TIME_ROUNDED, ':', 1, 2 ) + 1, INSTR(BILL_TIME_ROUNDED, ':', 1, 2 ) - INSTR(BILL_TIME_ROUNDED, ':', 1, 1 ) - 1 )))
           AS BILL_TIME_ROUNDED_IN_SECONDS,
       DIAL_TIME,
         (TO_NUMBER (SUBSTR(DIAL_TIME, 1, INSTR(DIAL_TIME, ':', 1, 1 ) - 1  )) * 60 * 60)
       + (TO_NUMBER (SUBSTR(DIAL_TIME, INSTR(DIAL_TIME, ':', 1, 1 ) + 1, INSTR(DIAL_TIME, ':', 1, 2 ) - INSTR(DIAL_TIME, ':', 1, 1 ) - 1 )) * 60)
       + (TO_NUMBER (SUBSTR(DIAL_TIME, INSTR(DIAL_TIME, ':', 1, 2 ) + 1, INSTR(DIAL_TIME, ':', 1, 2 ) - INSTR(DIAL_TIME, ':', 1, 1 ) - 1 )))   
           AS DIAL_TIME_IN_SECONDS,
       CALLS_COMPLETED_IN_IVR,
       CALLS_TIMED_OUT_IN_IVR,
       CONTACTED,
       DISPOSITION,
       DISPOSITION_PATH,
       DNIS,
       IVR_PATH,
       LIVE_CONNECT,
       NO_PARTY_CONTACT,
       NOTES,
       SPEED_OF_ANSWER,
         (TO_NUMBER (SUBSTR(SPEED_OF_ANSWER, 1, INSTR(SPEED_OF_ANSWER, ':', 1, 1 ) - 1  )) * 60 * 60)
       + (TO_NUMBER (SUBSTR(SPEED_OF_ANSWER, INSTR(SPEED_OF_ANSWER, ':', 1, 1 ) + 1, INSTR(SPEED_OF_ANSWER, ':', 1, 2 ) - INSTR(SPEED_OF_ANSWER, ':', 1, 1 ) - 1 )) * 60)
       + (TO_NUMBER (SUBSTR(SPEED_OF_ANSWER, INSTR(SPEED_OF_ANSWER, ':', 1, 2 ) + 1, INSTR(SPEED_OF_ANSWER, ':', 1, 2 ) - INSTR(SPEED_OF_ANSWER, ':', 1, 1 ) - 1 )))   
           AS SPEED_OF_ANSWER_IN_SECONDS,
       CONFERENCES,
       COST,         ---After-tax cost of calls that have a non-zero TALK TIME
       PREVIEW_TIME, ---Duration of a record preview by an agent before a call.
         (TO_NUMBER (SUBSTR(PREVIEW_TIME, 1, INSTR(PREVIEW_TIME, ':', 1, 1 ) - 1  )) * 60 * 60)
       + (TO_NUMBER (SUBSTR(PREVIEW_TIME, INSTR(PREVIEW_TIME, ':', 1, 1 ) + 1, INSTR(PREVIEW_TIME, ':', 1, 2 ) - INSTR(PREVIEW_TIME, ':', 1, 1 ) - 1 )) * 60)
       + (TO_NUMBER (SUBSTR(PREVIEW_TIME, INSTR(PREVIEW_TIME, ':', 1, 2 ) + 1, INSTR(PREVIEW_TIME, ':', 1, 2 ) - INSTR(PREVIEW_TIME, ':', 1, 1 ) - 1 )))   
           AS PREVIEW_TIME_IN_SECONDS,
       RATE,                                          ---Minute rate for call.
       TIME_TO_ABANDON,
           (TO_NUMBER (SUBSTR(TIME_TO_ABANDON, 1, INSTR(TIME_TO_ABANDON, ':', 1, 1 ) - 1  )) * 60 * 60)
       + (TO_NUMBER (SUBSTR(TIME_TO_ABANDON, INSTR(TIME_TO_ABANDON, ':', 1, 1 ) + 1, INSTR(TIME_TO_ABANDON, ':', 1, 2 ) - INSTR(TIME_TO_ABANDON, ':', 1, 1 ) - 1 )) * 60)
       + (TO_NUMBER (SUBSTR(TIME_TO_ABANDON, INSTR(TIME_TO_ABANDON, ':', 1, 2 ) + 1, INSTR(TIME_TO_ABANDON, ':', 1, 2 ) - INSTR(TIME_TO_ABANDON, ':', 1, 1 ) - 1 ))) 
           AS TIME_TO_ABANDON_IN_SECONDS,
       TOTAL_QUEUE_TIME,
          (TO_NUMBER (SUBSTR(TOTAL_QUEUE_TIME, 1, INSTR(TOTAL_QUEUE_TIME, ':', 1, 1 ) - 1  )) * 60 * 60)
       + (TO_NUMBER (SUBSTR(TOTAL_QUEUE_TIME, INSTR(TOTAL_QUEUE_TIME, ':', 1, 1 ) + 1, INSTR(TOTAL_QUEUE_TIME, ':', 1, 2 ) - INSTR(TOTAL_QUEUE_TIME, ':', 1, 1 ) - 1 )) * 60)
       + (TO_NUMBER (SUBSTR(TOTAL_QUEUE_TIME, INSTR(TOTAL_QUEUE_TIME, ':', 1, 2 ) + 1, INSTR(TOTAL_QUEUE_TIME, ':', 1, 2 ) - INSTR(TOTAL_QUEUE_TIME, ':', 1, 1 ) - 1 ))) 
           AS TOTAL_QUEUE_TIME_IN_SECONDS,
       QUEUE_WAIT_TIME,
         (TO_NUMBER ( SUBSTR( QUEUE_WAIT_TIME, 1, INSTR( QUEUE_WAIT_TIME, ':', 1, 1 ) - 1  )) * 60 * 60)
       + (TO_NUMBER (SUBSTR( QUEUE_WAIT_TIME, INSTR( QUEUE_WAIT_TIME, ':', 1, 1 ) + 1, INSTR( QUEUE_WAIT_TIME, ':', 1, 2 ) - INSTR( QUEUE_WAIT_TIME, ':', 1, 1 ) - 1 )) * 60)
      + (TO_NUMBER (SUBSTR( QUEUE_WAIT_TIME, INSTR( QUEUE_WAIT_TIME, ':', 1, 2 ) + 1, INSTR( QUEUE_WAIT_TIME, ':', 1, 2 ) - INSTR( QUEUE_WAIT_TIME, ':', 1, 1 ) - 1 )))
           AS QUEUE_WAIT_TIME_IN_SECONDS,
       AFTER_CALL_WORK_TIME,
         (TO_NUMBER ( SUBSTR(AFTER_CALL_WORK_TIME, 1, INSTR(AFTER_CALL_WORK_TIME, ':', 1, 1 ) - 1  )) * 60 * 60)
       + (TO_NUMBER (SUBSTR(AFTER_CALL_WORK_TIME, INSTR(AFTER_CALL_WORK_TIME, ':', 1, 1 ) + 1, INSTR( AFTER_CALL_WORK_TIME, ':', 1, 2 ) - INSTR(AFTER_CALL_WORK_TIME, ':', 1, 1 ) - 1 )) * 60)
       + (TO_NUMBER (SUBSTR(AFTER_CALL_WORK_TIME, INSTR(AFTER_CALL_WORK_TIME, ':', 1, 2 ) + 1, INSTR( AFTER_CALL_WORK_TIME, ':', 1, 2 ) - INSTR(AFTER_CALL_WORK_TIME, ':', 1, 1 ) - 1 )))
           AS AFTER_CALL_WORK_TIME_IN_SECONDS,
       TRANSFERS,
       VOICEMAILS,
       VOICEMAILS_DECLINED,
       VOICEMAILS_DELETED,
       VOICEMAILS_HANDLE_TIME,
            (TO_NUMBER ( SUBSTR(VOICEMAILS_HANDLE_TIME, 1, INSTR(VOICEMAILS_HANDLE_TIME, ':', 1, 1 ) - 1  )) * 60 * 60)
       + (TO_NUMBER (SUBSTR(VOICEMAILS_HANDLE_TIME, INSTR(VOICEMAILS_HANDLE_TIME, ':', 1, 1 ) + 1, INSTR( VOICEMAILS_HANDLE_TIME, ':', 1, 2 ) - INSTR(VOICEMAILS_HANDLE_TIME, ':', 1, 1 ) - 1 )) * 60)
       + (TO_NUMBER (SUBSTR(VOICEMAILS_HANDLE_TIME, INSTR(VOICEMAILS_HANDLE_TIME, ':', 1, 2 ) + 1, INSTR( VOICEMAILS_HANDLE_TIME, ':', 1, 2 ) - INSTR(VOICEMAILS_HANDLE_TIME, ':', 1, 1 ) - 1 )))
           AS VOICEMAILS_HANDLE_TIME_IN_SECONDS,
       VOICEMAILS_HANDLED,
       VOICEMAILS_RETURNED_CALL,
       VOICEMAILS_TRANSFERRED,
       DISCONNECTED_FROM_HOLD,
       --     TALK_TIME_LESS_HOLD_AND_PARK,
       NUMBER1,              ---Current primary phone number in a list record.
       SESSION_ID
  FROM DW_OWNER.F9_CALL_LOG  A
  JOIN MV_DIM_F9_SKILL       S ON (A.SKILL = S.SKILL)
  JOIN MV_DIM_F9_CAMPAIGN    C  ON (A.CAMPAIGN = C.CAMPAIGN);



GRANT SELECT ON CHOICEBI.MV_FACT_F9_CALL_LOG TO CHOICEBI_RO, CHOICEBI_RO_NEW, LINKADM, LINKADM2, MSTRSTG, ROC_RO, ROC_RO2;
