DROP MATERIALIZED VIEW CHOICEBI.MV_FACT_F9_CALL_SEGMENT;

CREATE MATERIALIZED VIEW CHOICEBI.MV_FACT_F9_CALL_SEGMENT 
AS 
SELECT DISTINCT
       CALL_ID,
       CALL_SEGMENT_ID,
       SEGMENT_TYPE,
       SEGMENT_TIME,
         (TO_NUMBER (SUBSTR(SEGMENT_TIME, 1, INSTR(SEGMENT_TIME, ':', 1, 1 ) - 1  )) * 60 * 60)
       + (TO_NUMBER (SUBSTR(SEGMENT_TIME, INSTR(SEGMENT_TIME, ':', 1, 1 ) + 1, INSTR(SEGMENT_TIME, ':', 1, 2 ) - INSTR(SEGMENT_TIME, ':', 1, 1 ) - 1 )) * 60)
       + (TO_NUMBER (SUBSTR(SEGMENT_TIME, INSTR(SEGMENT_TIME, ':', 1, 2 ) + 1, INSTR(SEGMENT_TIME, ':', 1, 2 ) - INSTR(SEGMENT_TIME, ':', 1, 1 ) - 1 )))
           AS SEGMENT_TIME_IN_SECONDS,
       TO_TIMESTAMP (SUBSTR (TIMESTAMP1, 6), 'DD MON YYYY HH24:MI:SS')
           TIMESTAMP,
       IVR_COST,  ---Post-tax cost for the time that a call spends in the IVR.
       IVR_RATE,
       IVR_TIME,
         (TO_NUMBER (SUBSTR(IVR_TIME, 1, INSTR(IVR_TIME, ':', 1, 1 ) - 1  )) * 60 * 60)
       + (TO_NUMBER (SUBSTR(IVR_TIME, INSTR(IVR_TIME, ':', 1, 1 ) + 1, INSTR(IVR_TIME, ':', 1, 2 ) - INSTR(IVR_TIME, ':', 1, 1 ) - 1 )) * 60)
       + (TO_NUMBER (SUBSTR(IVR_TIME, INSTR(IVR_TIME, ':', 1, 2 ) + 1, INSTR(IVR_TIME, ':', 1, 2 ) - INSTR(IVR_TIME, ':', 1, 1 ) - 1 )))
           AS IVR_TIME_IN_SECONDS,
       TALK_TIME,
         (TO_NUMBER (SUBSTR(TALK_TIME, 1, INSTR(TALK_TIME, ':', 1, 1 ) - 1  )) * 60 * 60)
       + (TO_NUMBER (SUBSTR(TALK_TIME, INSTR(TALK_TIME, ':', 1, 1 ) + 1, INSTR(TALK_TIME, ':', 1, 2 ) - INSTR(TALK_TIME, ':', 1, 1 ) - 1 )) * 60)
       + (TO_NUMBER (SUBSTR(TALK_TIME, INSTR(TALK_TIME, ':', 1, 2 ) + 1, INSTR(TALK_TIME, ':', 1, 2 ) - INSTR(TALK_TIME, ':', 1, 1 ) - 1 )))
           AS TALK_TIME_IN_SECONDS,
       CONFERENCE_TIME,
            (TO_NUMBER (SUBSTR(CONFERENCE_TIME, 1, INSTR(CONFERENCE_TIME, ':', 1, 1 ) - 1  )) * 60 * 60)
       + (TO_NUMBER (SUBSTR(CONFERENCE_TIME, INSTR(CONFERENCE_TIME, ':', 1, 1 ) + 1, INSTR(CONFERENCE_TIME, ':', 1, 2 ) - INSTR(CONFERENCE_TIME, ':', 1, 1 ) - 1 )) * 60)
       + (TO_NUMBER (SUBSTR(CONFERENCE_TIME, INSTR(CONFERENCE_TIME, ':', 1, 2 ) + 1, INSTR(CONFERENCE_TIME, ':', 1, 2 ) - INSTR(CONFERENCE_TIME, ':', 1, 1 ) - 1 )))
           AS CONFERENCE_TIME_IN_SECONDS,
       CONSULT_TIME,
         (TO_NUMBER (SUBSTR(CONSULT_TIME, 1, INSTR(CONSULT_TIME, ':', 1, 1 ) - 1  )) * 60 * 60)
       + (TO_NUMBER (SUBSTR(CONSULT_TIME, INSTR(CONSULT_TIME, ':', 1, 1 ) + 1, INSTR(CONSULT_TIME, ':', 1, 2 ) - INSTR(CONSULT_TIME, ':', 1, 1 ) - 1 )) * 60)
       + (TO_NUMBER (SUBSTR(CONSULT_TIME, INSTR(CONSULT_TIME, ':', 1, 2 ) + 1, INSTR(CONSULT_TIME, ':', 1, 2 ) - INSTR(CONSULT_TIME, ':', 1, 1 ) - 1 )))
           AS CONSULT_TIME_IN_SECONDS,
       THIRD_PARTY_TALK_TIME,
         (TO_NUMBER (SUBSTR(THIRD_PARTY_TALK_TIME, 1, INSTR(THIRD_PARTY_TALK_TIME, ':', 1, 1 ) - 1  )) * 60 * 60)
       + (TO_NUMBER (SUBSTR(THIRD_PARTY_TALK_TIME, INSTR(THIRD_PARTY_TALK_TIME, ':', 1, 1 ) + 1, INSTR(THIRD_PARTY_TALK_TIME, ':', 1, 2 ) - INSTR(THIRD_PARTY_TALK_TIME, ':', 1, 1 ) - 1 )) * 60)
       + (TO_NUMBER (SUBSTR(THIRD_PARTY_TALK_TIME, INSTR(THIRD_PARTY_TALK_TIME, ':', 1, 2 ) + 1, INSTR(THIRD_PARTY_TALK_TIME, ':', 1, 2 ) - INSTR(THIRD_PARTY_TALK_TIME, ':', 1, 1 ) - 1 )))
           AS THIRD_PARTY_TALK_TIME_IN_SECONDS,
       QUEUE_WAIT_TIME,
         (TO_NUMBER ( SUBSTR( QUEUE_WAIT_TIME, 1, INSTR( QUEUE_WAIT_TIME, ':', 1, 1 ) - 1  )) * 60 * 60)
       + (TO_NUMBER (SUBSTR( QUEUE_WAIT_TIME, INSTR( QUEUE_WAIT_TIME, ':', 1, 1 ) + 1, INSTR( QUEUE_WAIT_TIME, ':', 1, 2 ) - INSTR( QUEUE_WAIT_TIME, ':', 1, 1 ) - 1 )) * 60)
      + (TO_NUMBER (SUBSTR( QUEUE_WAIT_TIME, INSTR( QUEUE_WAIT_TIME, ':', 1, 2 ) + 1, INSTR( QUEUE_WAIT_TIME, ':', 1, 2 ) - INSTR( QUEUE_WAIT_TIME, ':', 1, 1 ) - 1 )))
           AS QUEUE_WAIT_TIME_IN_SECONDS,
        RING_TIME,
          (TO_NUMBER (SUBSTR(RING_TIME, 1, INSTR(RING_TIME, ':', 1, 1 ) - 1  )) * 60 * 60)
       + (TO_NUMBER (SUBSTR(RING_TIME, INSTR(RING_TIME, ':', 1, 1 ) + 1, INSTR(RING_TIME, ':', 1, 2 ) - INSTR(RING_TIME, ':', 1, 1 ) - 1 )) * 60)
       + (TO_NUMBER (SUBSTR(RING_TIME, INSTR(RING_TIME, ':', 1, 2 ) + 1, INSTR(RING_TIME, ':', 1, 2 ) - INSTR(RING_TIME, ':', 1, 1 ) - 1 )))
           AS RING_TIME_IN_SECONDS,
       --     TALK_TIME_LESS_HOLD_AND_PARK,
       --     (TO_NUMBER (SUBSTR (TALK_TIME_LESS_HOLD_AND_PARK, 1, 2)) * 60 * 60)
       --   + (TO_NUMBER (SUBSTR (TALK_TIME_LESS_HOLD_AND_PARK, 4, 2)) * 60)
       --   + (TO_NUMBER (SUBSTR (TALK_TIME_LESS_HOLD_AND_PARK, 7)))
       --       AS TALK_TIME_LESS_HOLD_AND_PARK_IN_SECONDS,
       HOLD_TIME,
         (TO_NUMBER (SUBSTR(HOLD_TIME, 1, INSTR(HOLD_TIME, ':', 1, 1 ) - 1  )) * 60 * 60)
       + (TO_NUMBER (SUBSTR(HOLD_TIME, INSTR(HOLD_TIME, ':', 1, 1 ) + 1, INSTR(HOLD_TIME, ':', 1, 2 ) - INSTR(HOLD_TIME, ':', 1, 1 ) - 1 )) * 60)
       + (TO_NUMBER (SUBSTR(HOLD_TIME, INSTR(HOLD_TIME, ':', 1, 2 ) + 1, INSTR(HOLD_TIME, ':', 1, 2 ) - INSTR(HOLD_TIME, ':', 1, 1 ) - 1 )))
           AS HOLD_TIME_IN_SECONDS,
       HOLDS,
       PARK_TIME,
         (TO_NUMBER (SUBSTR(PARK_TIME, 1, INSTR(PARK_TIME, ':', 1, 1 ) - 1  )) * 60 * 60)
       + (TO_NUMBER (SUBSTR(PARK_TIME, INSTR(PARK_TIME, ':', 1, 1 ) + 1, INSTR(PARK_TIME, ':', 1, 2 ) - INSTR(PARK_TIME, ':', 1, 1 ) - 1 )) * 60)
       + (TO_NUMBER (SUBSTR(PARK_TIME, INSTR(PARK_TIME, ':', 1, 2 ) + 1, INSTR(PARK_TIME, ':', 1, 2 ) - INSTR(PARK_TIME, ':', 1, 1 ) - 1 )))
           AS PARK_TIME_IN_SECONDS,
       PARKS,
       QUEUE_CALLBACK_WAIT_TIME,
       (TO_NUMBER (SUBSTR(QUEUE_CALLBACK_WAIT_TIME, 1, INSTR(QUEUE_CALLBACK_WAIT_TIME, ':', 1, 1 ) - 1  )) * 60 * 60)
       + (TO_NUMBER (SUBSTR(QUEUE_CALLBACK_WAIT_TIME, INSTR(QUEUE_CALLBACK_WAIT_TIME, ':', 1, 1 ) + 1, INSTR(QUEUE_CALLBACK_WAIT_TIME, ':', 1, 2 ) - INSTR(QUEUE_CALLBACK_WAIT_TIME, ':', 1, 1 ) - 1 )) * 60)
       + (TO_NUMBER (SUBSTR(QUEUE_CALLBACK_WAIT_TIME, INSTR(QUEUE_CALLBACK_WAIT_TIME, ':', 1, 2 ) + 1, INSTR(QUEUE_CALLBACK_WAIT_TIME, ':', 1, 2 ) - INSTR(QUEUE_CALLBACK_WAIT_TIME, ':', 1, 1 ) - 1 )))
           AS QUEUE_CALLBACK_WAIT_TIME_IN_SECONDS,
       RATE,
        TOTAL_QUEUE_TIME,
          (TO_NUMBER (SUBSTR(TOTAL_QUEUE_TIME, 1, INSTR(TOTAL_QUEUE_TIME, ':', 1, 1 ) - 1  )) * 60 * 60)
       + (TO_NUMBER (SUBSTR(TOTAL_QUEUE_TIME, INSTR(TOTAL_QUEUE_TIME, ':', 1, 1 ) + 1, INSTR(TOTAL_QUEUE_TIME, ':', 1, 2 ) - INSTR(TOTAL_QUEUE_TIME, ':', 1, 1 ) - 1 )) * 60)
       + (TO_NUMBER (SUBSTR(TOTAL_QUEUE_TIME, INSTR(TOTAL_QUEUE_TIME, ':', 1, 2 ) + 1, INSTR(TOTAL_QUEUE_TIME, ':', 1, 2 ) - INSTR(TOTAL_QUEUE_TIME, ':', 1, 1 ) - 1 ))) 
           AS TOTAL_QUEUE_TIME_IN_SECONDS,
       TRANSFERS,
       CALLED_PARTY,
       CALLING_PARTY,
       A.SKILL,
       S.DL_SKILL_SK,
       A.CAMPAIGN,
       C.DL_CAMPAIGN_SK,
       CAMPAIGN_TYPE,
       RESULT
  FROM DW_OWNER.F9_CALL_SEGMENT  A
  JOIN MV_DIM_F9_SKILL       S ON (A.SKILL = S.SKILL)
  JOIN MV_DIM_F9_CAMPAIGN    C  ON (A.CAMPAIGN = C.CAMPAIGN);

GRANT SELECT ON CHOICEBI.MV_FACT_F9_CALL_SEGMENT TO CHOICEBI_RO, CHOICEBI_RO_NEW, LINKADM, LINKADM2, MSTRSTG, ROC_RO, ROC_RO2;

