
---
SELECT  DISTINCT
        AGENT_ID,AGENT_GROUP, 
        AGENT_NAME,AGENT_FIRST_NAME,AGENT_LAST_NAME,AGENT,AGENT_EMAIL,AGENT_START_DATE,EXTENSION,ENABLED_FOR_VIDEO
FROM DW_OWNER.F9_AGENT
order by AGENT_ID;





---DIM_AGENT
SELECT 
    distinct
    B.staff_id, B.first_name,B.last_name, 
    B.staff_status, B.staff_type,B.employee_type, 
    B.company, B.company_id, B.cost_center, B.COST_CENTER_ID,
    B.job_title, B.job_family, B.region, 
    B.manager_id, B.STAFFS_MANAGER,
    C.first_name  manager_first_name, C.last_name  manager_last_name,
    A.agent_first_name, A.agent_last_name, A.agent_id, A.agent_start_date --,A.skill
FROM DW_OWNER.F9_AGENT A 
  JOIN DW_OWNER.CVX_STAFF B ON (UPPER(B.STAFFS_WORK_EMAIL) = UPPER(A.AGENT_EMAIL)) 
  JOIN DW_OWNER.CVX_STAFF C ON (B.MANAGER_ID = C.STAFF_ID)
WHERE TRIM(UPPER(A.AGENT_EMAIL)) LIKE '%VNSNY.ORG' AND B.STAFFS_WORK_EMAIL IS NOT NULL    
      ;


---AGENT_LOGIN

--CREATE VIEW CHOICEBI.VM_F9_AGENT_LOGIIN AS
SELECT AGENT_ID,
       DATE1,TIMESTAMP1,LOGIN_TIMESTAMP,LOGOUT_TIMESTAMP, AGENT_STATES,STATE,AGENT_STATE_TIME, REASON_CODE,SKILL_AVAILABILITY,
       LOGIN_TIME,LOGOUT_TIME,MANUAL_TIME,NOT_READY_TIME,ON_ACW_TIME,ON_CALL_TIME,ON_VOICEMAIL_TIME,PAID_TIME,READY_TIME,RINGING_TIME,
       AVAILABLE_FOR_ALL,  AVAILABLE_FOR_CALLS, AVAILABLE_FOR_VM, MEDIA_AVAILABILITY, UNAVAILABLE_FOR_CALLS, UNAVAILABLE_FOR_VM,       
       UNPAID_TIME,VIDEO_TIME,VM_IN_PROGRESS_TIME,WAIT_TIME, AGENT_DISCONNECTS_FIRST,SHORT_CALLS
FROM DW_OWNER.F9_AGENT
;  

SELECT *
FROM DW_OWNER.F9_AGENT
WHERE AGENT_ID IN (SELECT  DISTINCT AGENT_ID FROM DW_OWNER.F9_AGENT WHERE AGENT = '[Deleted]');

select * from DW_OWNER.F9_AGENT;