
---- call_log_details
SELECT CALL_ID,   AGENT_ID,  date1,  ----
       TIMESTAMP1,CALL_TYPE,CALLS, CAMPAIGN, CAMPAIGN_TYPE, SKILL,	VNSNY_SKILLNAME,
       ANI,DNIS,DISPOSITION,DISPOSITION_GROUP_A, DISPOSITION_GROUP_B, DISPOSITION_GROUP_C, DISPOSITION_PATH,       
       CALL_TIME,DIAL_TIME,RING_TIME, HANDLE_TIME,TALK_TIME,HOLD_TIME,AFTER_CALL_WORK_TIME,	CALL_SURVEY_RESULT,SPEED_OF_ANSWER,BILL_TIME_ROUNDED,
       CONFERENCE_TIME, CONFERENCES, CONSULT_TIME, COST,  HOLDS, IVR_COST, IVR_RATE, IVR_TIME, MANUAL_TIME, PARK_TIME, PARKS,       
       ABANDON_RATE, ABANDONED,RECORDINGS,
       CALLS_COMPLETED_IN_IVR, CALLS_TIMED_OUT_IN_IVR,LIST_NAME, 
       LIVE_CONNECT, NO_PARTY_CONTACT,NOTES,TALK_TIME_LESS_HOLD_AND_PARK, TIME_TO_ABANDON, TOTAL_QUEUE_TIME, TRANSFERS, SESSION_ID,
       VIDEO_TIME, VOICEMAILS, VOICEMAILS_DECLINED, VOICEMAILS_DELETED, VOICEMAILS_HANDLE_TIME, VOICEMAILS_HANDLED, VOICEMAILS_RETURNED_CALL, VOICEMAILS_TRANSFERRED ,   
       CONTACTED,CONTACT_ID,CONTACT_CREATE_TIMESTAMP,CONTACT_MODIFIED_TIMESTAMP --,CUSTOMER_NAME,NUMBER1,NUMBER2, NUMBER3, STATE, STREET, ZIP,
FROM DW_OWNER.F9_CALL_LOG
;






select distinct 
 CAMPAIGN_TYPE,CAMPAIGN, SKILL --leader, LOB
FROM DW_OWNER.F9_CALL_LOG
where skill = 'CCC Active Patient Eng';





SELECT CALL_ID,   AGENT_ID,    ----
       TIMESTAMP1,CALL_TYPE,CALLS, CAMPAIGN, CAMPAIGN_TYPE, SKILL,	VNSNY_SKILLNAME,
       ANI,DNIS,DISPOSITION,DISPOSITION_GROUP_A, DISPOSITION_GROUP_B, DISPOSITION_GROUP_C, DISPOSITION_PATH,       
       CALL_TIME,DIAL_TIME,RING_TIME, HANDLE_TIME,TALK_TIME,HOLD_TIME,AFTER_CALL_WORK_TIME,	CALL_SURVEY_RESULT,SPEED_OF_ANSWER,BILL_TIME_ROUNDED,
       CONFERENCE_TIME, CONFERENCES, CONSULT_TIME, COST,  HOLDS, IVR_COST, IVR_RATE, IVR_TIME, MANUAL_TIME, PARK_TIME, PARKS,       
       ABANDON_RATE, ABANDONED,RECORDINGS,
       CALLS_COMPLETED_IN_IVR, CALLS_TIMED_OUT_IN_IVR,LIST_NAME, 
       LIVE_CONNECT, NO_PARTY_CONTACT,NOTES,TALK_TIME_LESS_HOLD_AND_PARK, TIME_TO_ABANDON, TOTAL_QUEUE_TIME, TRANSFERS, SESSION_ID,
       VIDEO_TIME, VOICEMAILS, VOICEMAILS_DECLINED, VOICEMAILS_DELETED, VOICEMAILS_HANDLE_TIME, VOICEMAILS_HANDLED, VOICEMAILS_RETURNED_CALL, VOICEMAILS_TRANSFERRED ,   
       CONTACTED,CONTACT_ID,CONTACT_CREATE_TIMESTAMP,CONTACT_MODIFIED_TIMESTAMP --,CUSTOMER_NAME,NUMBER1,NUMBER2, NUMBER3, STATE, STREET, ZIP,
FROM DW_OWNER.F9_CALL_LOG
WHERE AGENT_ID IN (SELECT  DISTINCT AGENT_ID FROM DW_OWNER.F9_AGENT WHERE AGENT = '[Deleted]');