MERGE INTO MV_DIM_F9_SKILL A USING
(
select distinct * from
(
SELECT DISTINCT SKILL FROM DW_OWNER.F9_CALL_LOG WHERE SKILL IS NOT NULL
UNION ALL
SELECT DISTINCT SKILL FROM DW_OWNER.F9_ACD_QUEUE WHERE SKILL IS NOT NULL
UNION ALL
SELECT DISTINCT SKILL FROM DW_OWNER.F9_CALL_SEGMENT WHERE SKILL IS NOT NULL
UNION ALL
SELECT DISTINCT SKILL FROM DW_OWNER.F9_AGENT WHERE SKILL IS NOT NULL
union all
SELECT DISTINCT SKILL FROM CHOICEBI.V_DIM_F9_AGENT_SKILL_MAP WHERE SKILL IS NOT NULL
)
) B
ON (A.SKILL = B.SKILL)
WHEN NOT MATCHED THEN
INSERT (
dl_skill_sk,
SKILL)
VALUES
(
SEQ_F9_SKILL.NEXTVAL,
B.SKILL
);

MERGE INTO MV_DIM_F9_CAMPAIGN A USING
(
select distinct * from
(
SELECT DISTINCT CAMPAIGN FROM DW_OWNER.F9_CALL_LOG WHERE SKILL IS NOT NULL
UNION ALL
SELECT DISTINCT CAMPAIGN FROM DW_OWNER.F9_ACD_QUEUE WHERE SKILL IS NOT NULL
UNION ALL
SELECT DISTINCT CAMPAIGN FROM DW_OWNER.F9_CALL_SEGMENT WHERE SKILL IS NOT NULL
UNION ALL
SELECT DISTINCT CAMPAIGN FROM DW_OWNER.F9_AGENT WHERE SKILL IS NOT NULL
)
) B
ON (A.CAMPAIGN = B.CAMPAIGN)
WHEN NOT MATCHED THEN
INSERT (
dl_CAMPAIGN_sk,
CAMPAIGN)
VALUES
(
SEQ_F9_CAMPAIGN.NEXTVAL,
B.CAMPAIGN
);

