select * from choice.FCT_CLAIM_MI_CBD@dlake; --
SELECT * FROM CHOICE.FCT_CLAIM_MI_DCT@DLAKE; --
SELECT * FROM CHOICE.FCT_CLAIM_MI_COB@DLAKE;--CLAIM_STATUS
SELECT * FROM CHOICE.FCT_CLAIM_MI_CST@DLAKE;--
SELECT * FROM CHOICE.FCT_CLAIM_MI_FDB@DLAKE;--
SELECT * FROM CHOICE.FCT_CLAIM_MI_CBP@DLAKE;--
SELECT * FROM CHOICE.FCT_CLAIM_MI_MSP@DLAKE; --GPID ,INGREDIENTSEQ_NUM
SELECT * FROM CHOICE.FCT_CLAIM_MI_DST@DLAKE;--
SELECT *FROM CHOICE.FCT_CLAIM_MI_DRG@DLAKE;-- QTY_DISPENSED  ,INGREDIENT_TYPE
select * from CHOICE.FCT_CLAIM_MI_BSA@DLAKE;--
select * from CHOICE.FCT_CLAIM_MI_CLR@DLAKE; ---REJECT_CD
SELECT * FROM CHOICE.FCT_CLAIM_MI_CBS@DLAKE; --BLANK
SELECT * FROM CHOICE.FCT_CLAIM_MI_CBR@DLAKE; ---OTHERPAYER_REJECTCD

SELECT * FROM CHOICE.FCT_CLAIM_MI@DLAKE;--CLAIM_PRESCRIPTION_NUM,CLAIM_SOURCE_CD





SELECT * FROM CHOICEBI.FCT_CLAIM_DIAGNOSIS;





SELECT * FROM CHOICE.DIM_MEMBER@DLAKE;

SELECT * FROM CHOICEBI.FCT_CLAIM_UNIVERSE_CURR;
