select * from choicebi.FCT_CLAIM_DOH_RX_CLAIM_INFO; --PHARMACY PROVIDER ID =vendor_id_billing_provider
select * from choicebi.FCT_CLAIM_DOH_RX_BILLING_PROVIDER_INFO; --vendor_provider = billing_provider = pharmacy
select * from choicebi.FCT_CLAIM_DOH_RX_CLAIMS_DIAG_GRP; --
SELECT * FROM CHOICEBI.FCT_CLAIM_DOH_RX_DUR_ADDL_GRP;--
select * from FCT_CLAIM_DOH_RX_DUR_DATA_GRP;--
select * from FCT_CLAIM_DOH_RX_EDIT_REJECT_GRP;--
SELECT * FROM FCT_CLAIM_DOH_RX_MNGCARE_PROV_INFO;--
SELECT * FROM FCT_CLAIM_DOH_RX_PAHID_REJECT_GRP;--
SELECT * FROM FCT_CLAIM_DOH_RX_PAYMENT_INFO ; --
SELECT * FROM FCT_CLAIM_DOH_RX_PA_REJECT_GRP ;--
SELECT * FROM FCT_CLAIM_DOH_RX_PRESCR_PROV_INFO; -- prescriber_id(NPI) DOC
SELECT * FROM FCT_CLAIM_DOH_RX_PRIOR_AUTH_INFO;--
select * from FCT_CLAIM_DOH_RX_REFER_DRUG_INFO;--


SELECT * FROM ALL_TAB_COLUMNS
WHERE COLUMN_NAME LIKE '%STRENGTH_VOLUME_NUMBER%'
AND OWNER ='CHOICEBI'
--AND TABLE_NAME LIKE '%MI%';


SELECT ROUTE_DESC,STRENGTH_VOLUME_NUMBER FROM DIM_RX_DRUG_CODES;

SELECT * FROM FCT_CLAIM_UNIVERSE_CURR_SH_VBP;

SELECT LOB FROM FCT_CLAIM_LINE_UNIVERSE_CURR; --CLAIM_STATUS,CLAIM_LINE_SEQ_NUM,CLAIM_STATUS,CLAIM_STATUS_DESC


SELECT * FROM CHOICEBI.FCT_CLAIM_MI;

SELECT * FROM CHOICEBI.FCT_CLAIM_UNIVERSE;--PRE_AUTH_NO,ADJUDICATION_DT,REFER_PHYSICIAN_NPI

SELECT * FROM CHOICEBI.DIM_ISSUER_SUBMISSION
WHERE DIM_ISSUER_SUBMISSION_SK =2;


SELECT * FROM CHOICEBI.DIM_RX_DRUG_CODES;

SELECT PRODID FROM CHOICEBI.FCT_CLAIM_MI_DRG;

SELECT * FROM CHOICEBI.FCT_CLAIM_MI_CST;

SELECT * FROM CHOICEBI.FCT_CLAIM_MI_DST;


SELECT PAN_APPROVAL_NUM,
PAN_PATYPE_CD,
PAN_SUBMITTEDPA_CDNUM,
PAN_PASTATUS_CD1,
PAN_PASTATUS_CD2,
PAN_PASTATUS_CD3
FROM FCT_CLAIM_MI;


SELECT * FROM CHOICE.Ref_claim_doh@DLAKE
WHERE DOH_CLAIM_TYPE = 'CLAIM_STATUS';
